const test=require('node:test'),assert=require('node:assert/strict'),R=require('../rhythm.js');
const g={bpm:120,meter:4,denominator:4,bars:4,subdivision:16,offset:.25,section:'verse'};
test('quarter-beat clock roundtrip and meter denominator',()=>{assert.equal(R.seconds(4,g),2.25);assert.equal(R.position(2.25,g),4);assert.equal(R.barLength({...g,meter:6,denominator:8}),3);});
test('invalid grid is rejected',()=>{for(const bad of [{bpm:0},{offset:-1},{subdivision:12},{bars:100},{denominator:3}])assert.throws(()=>R.validate({...g,...bad}));});
test('blank lyric line preserves a bar rest and words never treated as performance',()=>{const l=R.map('Hello world\n\nHere we go',g);assert.equal(l[1].words.length,0);assert.equal(l[2].start,8);assert.equal(R.context('x',l,g,'rewrite').timingBasis.includes('not recorded'),true);});
test('syllable overrides produce word and syllable placements',()=>{const l=R.map('Hello world',g)[0];l.words[0].syllables=2;l.words[1].syllables=1;l.duration=3;assert.equal(R.tokens(l)[1].start,2);assert.deepEqual(R.tokens(l)[0].landings,[0,1]);});
test('intentional push/pull survives analysis without good/bad score',()=>{const l=R.map('Hello world',g);l[0].push=-.25;l[0].intent='anticipation';const a=R.analyze(l,g)[0];assert.equal(a.start,-.25);assert.equal(a.intent,'anticipation');assert.equal('score' in a,false);assert.equal(a.crosses,true);});
test('flow reuse keeps new words, cycles cadence, rejects different meter',()=>{const l=R.map('One\nTwo',g),p=R.capture(l,g);const applied=R.apply(R.map('Three\nFour\nFive',g),p,g);assert.equal(applied[2].start,8);assert.equal(applied[2].words[0].text,'Five');assert.throws(()=>R.apply(l,p,{...g,meter:3}));});
test('writing context contains real grid, phrase timing, rhyme and request',()=>{const l=R.map('Hold the light',g),c=R.context('Hold the light',l,g,'less crowded');assert.equal(c.task,'less crowded');assert.equal(c.grid.bpm,120);assert.equal(c.pocket[0].rhyme,'light');assert.equal(c.phrases[0].duration,3.2);});
